BEGIN TRANSACTION;
ALTER TABLE "users" ADD COLUMN "age" INTEGER NOT NULL;
ALTER TABLE "users" ADD COLUMN "gender" TEXT NOT NULL CHECK(gender IN ('male', 'female', 'other'));
ALTER TABLE "users" ADD COLUMN "first_name" TEXT NOT NULL;
ALTER TABLE "users" ADD COLUMN "last_name" TEXT NOT NULL;
END TRANSACTION;
