BEGIN TRANSACTION;
ALTER TABLE "users" ADD COLUMN "age" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "users" ADD COLUMN "gender" TEXT NOT NULL CHECK(gender IN ('male', 'female', 'other')) DEFAULT 'other';
ALTER TABLE "users" ADD COLUMN "first_name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "users" ADD COLUMN "last_name" TEXT NOT NULL DEFAULT '';
END TRANSACTION;
